# TeX atom classification tables used by layout.jl.

# Characters whose ASCII/Latin-1 codepoints differ from their correct math-mode
# glyph.  Applied only in math mode; text mode uses the literal codepoint.
const _MATH_CHAR_REMAP = Dict{Char, Char}(
    '-' => '−',   # U+002D HYPHEN-MINUS  → U+2212 MINUS SIGN
    '*' => '∗',   # U+002A ASTERISK      → U+2217 ASTERISK OPERATOR
)

# Inter-atom spacing follows TeX's eight atom classes (Knuth, Chapter 17) and
# KaTeX's spacingData.ts.  Characters/commands not listed default to :ord.
# _MATH_CHAR_REMAP is applied before char lookup so '-' and '−' both yield :bin.
const _CHAR_ATOM_CLASS = Dict{Char, Symbol}(
    # Binary operators
    '+' => :bin,
    '-' => :bin,    # U+002D (also remapped to U+2212 for glyph lookup)
    '−' => :bin,    # U+2212 MINUS SIGN
    '*' => :bin,    # U+002A (remapped to U+2217)
    '∗' => :bin,    # U+2217 ASTERISK OPERATOR
    '×' => :bin, '÷' => :bin,
    '·' => :bin, '±' => :bin,
    '∓' => :bin, '∧' => :bin,
    '∨' => :bin, '∩' => :bin,
    '∪' => :bin, '⊕' => :bin,
    '⊖' => :bin, '⊗' => :bin,
    '⊘' => :bin, '⊙' => :bin,
    '∘' => :bin, '•' => :bin,
    '⋆' => :bin, '†' => :bin,
    '‡' => :bin,
    # Relations
    '=' => :rel, '<' => :rel,
    '>' => :rel, ':' => :rel,
    '≤' => :rel, '≥' => :rel,
    '≠' => :rel, '≈' => :rel,
    '∼' => :rel, '≃' => :rel,
    '≅' => :rel, '∝' => :rel,
    '⊥' => :rel, '∥' => :rel,
    '∣' => :rel, '⊂' => :rel,
    '⊃' => :rel, '⊆' => :rel,
    '⊇' => :rel, '∈' => :rel,
    '∉' => :rel, '∋' => :rel,
    '→' => :rel, '←' => :rel,
    '↔' => :rel, '⇒' => :rel,
    '⇐' => :rel, '⇔' => :rel,
    '↦' => :rel, '≡' => :rel,
    '≺' => :rel, '≻' => :rel,
    '≪' => :rel, '≫' => :rel,
    '⊢' => :rel, '⊣' => :rel,
    '⊨' => :rel, '↑' => :rel,
    '↓' => :rel, '⇑' => :rel,
    '⇓' => :rel,
    # Open delimiters
    '(' => :open, '[' => :open,
    # Close delimiters
    ')' => :close, ']' => :close,
    '!' => :close,
    # Punctuation
    ',' => :punct, ';' => :punct,
    # Inner (ellipses)
    '…' => :inner, '⋯' => :inner,
    '⋱' => :inner,
)

# Atom class by command name (bare, without leading backslash).
const _CMD_ATOM_CLASS = Dict{String, Symbol}(
    # ── Binary operators ────────────────────────────────────────────────────
    "pm" => :bin, "mp" => :bin,
    "times" => :bin, "div" => :bin,
    "cdot" => :bin, "ast" => :bin,
    "star" => :bin, "circ" => :bin,
    "bullet" => :bin,
    "cap" => :bin, "cup" => :bin,
    "sqcap" => :bin, "sqcup" => :bin,
    "wedge" => :bin, "land" => :bin,
    "vee" => :bin, "lor" => :bin,
    "setminus" => :bin, "smallsetminus" => :bin,
    "oplus" => :bin, "ominus" => :bin,
    "otimes" => :bin, "oslash" => :bin,
    "odot" => :bin,
    "boxplus" => :bin, "boxminus" => :bin,
    "boxtimes" => :bin, "boxdot" => :bin,
    "ltimes" => :bin, "rtimes" => :bin,
    "wr" => :bin, "amalg" => :bin,
    "dagger" => :bin, "ddagger" => :bin,
    "dag" => :bin, "ddag" => :bin,
    "triangleleft" => :bin, "triangleright" => :bin,
    "barwedge" => :bin, "curlywedge" => :bin,
    "curlyvee" => :bin, "intercal" => :bin,
    "dotplus" => :bin, "leftthreetimes" => :bin,
    "rightthreetimes" => :bin, "doublebarwedge" => :bin,
    "divideontimes" => :bin,

    # ── Relations ───────────────────────────────────────────────────────────
    "leq" => :rel, "le" => :rel,
    "geq" => :rel, "ge" => :rel,
    "neq" => :rel, "ne" => :rel,
    "equiv" => :rel, "approx" => :rel,
    "sim" => :rel, "simeq" => :rel,
    "cong" => :rel, "propto" => :rel,
    "perp" => :rel, "parallel" => :rel,
    "mid" => :rel, "nmid" => :rel,
    "subset" => :rel, "supset" => :rel,
    "subseteq" => :rel, "supseteq" => :rel,
    "sqsubseteq" => :rel, "sqsupseteq" => :rel,
    "in" => :rel, "notin" => :rel,
    "ni" => :rel, "owns" => :rel,
    "prec" => :rel, "succ" => :rel,
    "preceq" => :rel, "succeq" => :rel,
    "ll" => :rel, "gg" => :rel,
    "lll" => :rel, "ggg" => :rel,
    "to" => :rel,
    "leftarrow" => :rel, "rightarrow" => :rel,
    "Leftarrow" => :rel, "Rightarrow" => :rel,
    "leftrightarrow" => :rel, "Leftrightarrow" => :rel,
    "longleftarrow" => :rel, "longrightarrow" => :rel,
    "Longleftarrow" => :rel, "Longrightarrow" => :rel,
    "longleftrightarrow" => :rel, "Longleftrightarrow" => :rel,
    "iff" => :rel, "implies" => :rel,
    "mapsto" => :rel, "longmapsto" => :rel,
    "hookleftarrow" => :rel, "hookrightarrow" => :rel,
    "uparrow" => :rel, "downarrow" => :rel,
    "Uparrow" => :rel, "Downarrow" => :rel,
    "updownarrow" => :rel, "Updownarrow" => :rel,
    "nearrow" => :rel, "searrow" => :rel,
    "swarrow" => :rel, "nwarrow" => :rel,
    "vdash" => :rel, "dashv" => :rel,
    "models" => :rel,
    "smile" => :rel, "frown" => :rel,
    "asymp" => :rel, "bowtie" => :rel,
    "Join" => :rel, "not" => :rel,
    "nleq" => :rel, "ngeq" => :rel,
    "nless" => :rel, "ngtr" => :rel,
    "nsim" => :rel, "nparallel" => :rel,
    "nsubseteq" => :rel, "nsupseteq" => :rel,
    "subsetneq" => :rel, "supsetneq" => :rel,
    "varsubsetneq" => :rel, "varsupsetneq" => :rel,
    "lneq" => :rel, "gneq" => :rel,
    "lnsim" => :rel, "gnsim" => :rel,
    "preccurlyeq" => :rel, "succcurlyeq" => :rel,
    "curlyeqprec" => :rel, "curlyeqsucc" => :rel,
    "sqsubset" => :rel, "sqsupset" => :rel,
    "Supset" => :rel, "Subset" => :rel,
    "trianglelefteq" => :rel, "trianglerighteq" => :rel,
    "vartriangleleft" => :rel, "vartriangleright" => :rel,
    "blacktriangleleft" => :rel, "blacktriangleright" => :rel,
    "leqq" => :rel, "geqq" => :rel,
    "leqslant" => :rel, "geqslant" => :rel,
    "eqslantless" => :rel, "eqslantgtr" => :rel,
    "lesssim" => :rel, "gtrsim" => :rel,
    "lessapprox" => :rel, "gtrapprox" => :rel,
    "approxeq" => :rel,
    "lessdot" => :rel, "gtrdot" => :rel,
    "lessgtr" => :rel, "gtrless" => :rel,
    "lesseqgtr" => :rel, "gtreqless" => :rel,
    "lesseqqgtr" => :rel, "gtreqqless" => :rel,
    "doteq" => :rel, "doteqdot" => :rel,
    "risingdotseq" => :rel, "fallingdotseq" => :rel,
    "backsim" => :rel, "backsimeq" => :rel,
    "eqcirc" => :rel, "circeq" => :rel,
    "triangleq" => :rel,
    "bumpeq" => :rel, "Bumpeq" => :rel,
    "thicksim" => :rel, "thickapprox" => :rel,
    "supseteqq" => :rel, "subseteqq" => :rel,
    "shortparallel" => :rel, "between" => :rel,
    "pitchfork" => :rel, "therefore" => :rel,
    "because" => :rel, "shortmid" => :rel,
    "backepsilon" => :rel, "varpropto" => :rel,
    "nleqslant" => :rel, "ngeqslant" => :rel,
    "nleqq" => :rel, "ngeqq" => :rel,
    "lvertneqq" => :rel, "gvertneqq" => :rel,
    "nprec" => :rel, "nsucc" => :rel,
    "npreceq" => :rel, "nsucceq" => :rel,

    # ── Large operators ─────────────────────────────────────────────────────
    "int" => :op, "iint" => :op,
    "iiint" => :op, "iiiint" => :op,
    "oint" => :op, "oiint" => :op,
    "oiiint" => :op,
    "sum" => :op, "prod" => :op,
    "coprod" => :op,
    "bigcap" => :op, "bigcup" => :op,
    "bigsqcup" => :op, "bigsqcap" => :op,
    "bigwedge" => :op, "bigvee" => :op,
    "bigoplus" => :op, "bigotimes" => :op,
    "bigodot" => :op, "biguplus" => :op,
    "bigplus" => :op,

    # ── Manual delimiter sizing ──────────────────────────────────────────────
    "bigl" => :open, "Bigl" => :open,
    "biggl" => :open, "Biggl" => :open,
    "bigr" => :close, "Bigr" => :close,
    "biggr" => :close, "Biggr" => :close,
    "bigm" => :rel, "Bigm" => :rel,
    "biggm" => :rel, "Biggm" => :rel,

    # ── Open delimiters ─────────────────────────────────────────────────────
    "{" => :open,
    "langle" => :open,
    "lfloor" => :open,
    "lceil" => :open,
    "lvert" => :open,
    "lVert" => :open,
    "lgroup" => :open,
    "lmoustache" => :open,
    "llbracket" => :open,

    # ── Close delimiters ────────────────────────────────────────────────────
    "}" => :close,
    "rangle" => :close,
    "rfloor" => :close,
    "rceil" => :close,
    "rvert" => :close,
    "rVert" => :close,
    "rgroup" => :close,
    "rmoustache" => :close,
    "rrbracket" => :close,

    # ── Punctuation ─────────────────────────────────────────────────────────
    "colon" => :punct,
    "cdotp" => :punct,
    "ldotp" => :punct,

    # ── Inner (ellipses, \bmod, \pmod) ──────────────────────────────────────
    "ldots" => :inner,
    "cdots" => :inner,
    "ddots" => :inner,
    "dots" => :inner,
    "dotsb" => :inner,
    "dotsc" => :inner,
    "dotsi" => :inner,
    "dotsm" => :inner,
    "dotso" => :inner,
    "bmod" => :inner,
    "pmod" => :inner,

    # ── Ordinary symbols ────────────────────────────────────────────────────
    # Greek lowercase
    "alpha" => :ord, "beta" => :ord,
    "gamma" => :ord, "delta" => :ord,
    "epsilon" => :ord, "varepsilon" => :ord,
    "zeta" => :ord, "eta" => :ord,
    "theta" => :ord, "vartheta" => :ord,
    "iota" => :ord, "kappa" => :ord,
    "lambda" => :ord, "mu" => :ord,
    "nu" => :ord, "xi" => :ord,
    "pi" => :ord, "varpi" => :ord,
    "rho" => :ord, "varrho" => :ord,
    "sigma" => :ord, "varsigma" => :ord,
    "tau" => :ord, "upsilon" => :ord,
    "phi" => :ord, "varphi" => :ord,
    "chi" => :ord, "psi" => :ord,
    "omega" => :ord,
    # Greek uppercase
    "Gamma" => :ord, "Delta" => :ord,
    "Theta" => :ord, "Lambda" => :ord,
    "Xi" => :ord, "Pi" => :ord,
    "Sigma" => :ord, "Upsilon" => :ord,
    "Phi" => :ord, "Psi" => :ord,
    "Omega" => :ord,
    # Miscellaneous ordinary symbols
    "infty" => :ord, "partial" => :ord,
    "nabla" => :ord, "forall" => :ord,
    "exists" => :ord, "nexists" => :ord,
    "emptyset" => :ord, "varnothing" => :ord,
    "angle" => :ord, "measuredangle" => :ord,
    "sphericalangle" => :ord,
    "ell" => :ord,
    "imath" => :ord, "jmath" => :ord,
    "hbar" => :ord, "hslash" => :ord,
    "Re" => :ord, "Im" => :ord,
    "wp" => :ord,
    "aleph" => :ord, "beth" => :ord,
    "gimel" => :ord, "daleth" => :ord,
    "prime" => :ord, "backprime" => :ord,
    "complement" => :ord,
    "surd" => :ord,
    "top" => :ord, "bot" => :ord,
    "flat" => :ord, "natural" => :ord,
    "sharp" => :ord,
    "diagup" => :ord, "diagdown" => :ord,
    "eth" => :ord,
    "Finv" => :ord, "Game" => :ord,
    "Bbbk" => :ord,
    "triangle" => :ord, "triangledown" => :ord,
    "square" => :ord, "blacksquare" => :ord,
    "lozenge" => :ord, "blacklozenge" => :ord,
    "bigstar" => :ord,
    "clubsuit" => :ord, "diamondsuit" => :ord,
    "heartsuit" => :ord, "spadesuit" => :ord,
    "checkmark" => :ord,
    "vert" => :ord, "Vert" => :ord,
    "backslash" => :ord,
    "S" => :ord, "P" => :ord,
    "copyright" => :ord, "circledR" => :ord,
    "maltese" => :ord,
    "yen" => :ord, "pounds" => :ord,
    "mho" => :ord, "Angstrom" => :ord,
    "digamma" => :ord, "varkappa" => :ord,
    "circledS" => :ord, "degree" => :ord,
    "textdollar" => :ord,
    "vdots" => :ord,  # vertical — ordinary, not inner like \cdots
    # Accents (base is an ordinary atom in terms of spacing)
    "hat" => :ord, "bar" => :ord,
    "vec" => :ord, "dot" => :ord,
    "ddot" => :ord, "tilde" => :ord,
    "widehat" => :ord, "widetilde" => :ord,
    "overline" => :ord, "underline" => :ord,
    # Font-mode selectors: the result is an ordinary atom
    "mathbf" => :ord, "mathrm" => :ord,
    "mathit" => :ord, "mathbb" => :ord,
    "mathcal" => :ord, "mathfrak" => :ord,
    "mathsf" => :ord, "mathtt" => :ord,
    "boldsymbol" => :ord, "text" => :ord,
    "mbox" => :ord,
)
